spring.application.name=SpringBootAPI
server.port=8012

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Connect Database (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WebProgrammingAPI;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA & Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# =============================== 
# FILE UPLOAD 
# =============================== 
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


# Storage location cho việc lưu file upload (icon, images...)
storage.location=uploads